name: Minesweeper Pipeline

on:
  push:
    branches:
      - "**"

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17